name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ubuntu-18.04
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: gcjam 2019 - npm install and test
      run: docker run -v $(pwd)/2019:/app -w /app/test node /bin/bash -c "npm install && npm test"s

    - name: gcjam 2020 - npm install and test
      run: docker run -v $(pwd)/2020:/app -w /app/test node /bin/bash -c "npm install && npm test"

    - name: gcjam 2021 - npm install and test
      run: docker run -v $(pwd)/2021:/app -w /app/test node /bin/bash -c "npm install && npm test"
