name: Create code from template

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create:
    name: Create code from template
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: test-create
      run: ./bin/test-create
